# Generated by Django 4.2.5 on 2023-09-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productlesson',
            options={'verbose_name': 'Продукт-Урок', 'verbose_name_plural': 'Продукты-Уроки'},
        ),
    ]
