# Generated by Django 4.2.5 on 2023-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='users_added',
            new_name='users',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='product x', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='viewing_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='time_watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
