# Generated by Django 4.2.5 on 2023-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='view',
            options={'verbose_name': 'Просмотр', 'verbose_name_plural': 'Просмотры'},
        ),
        migrations.RenameField(
            model_name='view',
            old_name='viewing_percent',
            new_name='time_watched',
        ),
        migrations.AddField(
            model_name='view',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
