# Generated by Django 4.2.5 on 2023-09-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_rename_users_added_product_users_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonview',
            name='is_viewed',
        ),
    ]
