# Generated by Django 4.2.5 on 2023-09-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lessonview_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_viewed_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=ACUUWJPSaiI'),
            preserve_default=False,
        ),
    ]
