# Generated by Django 4.2.5 on 2023-09-21 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0004_lessonview_last_viewed_date_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.ManyToManyField(through='lessons.LessonView', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='allowed_users', through='lessons.Access', to=settings.AUTH_USER_MODEL),
        ),
    ]
