# Generated by Django 4.2.5 on 2023-09-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_views_alter_product_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
