# Generated by Django 4.2.5 on 2023-09-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessonview_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonview',
            name='is_viewed',
        ),
    ]
