# Generated by Django 4.2.5 on 2023-09-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_lessonview_is_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='viewing_time',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='lessonview',
            old_name='time_watched',
            new_name='view_time',
        ),
    ]
